#!/usr/bin/env bash
# issue.sh — bash version of /opt/iot-cert/issue.py
# Issues a TLS client cert signed by the HTL-IoT CA, updates the broker
# ACL, drops a ready-to-use bundle in /opt/iot-cert/issued/<name>/.
#
# Usage:
#   sudo ./issue.sh                           # interactive
#   sudo ./issue.sh NAME PUB SUB              # one-shot
# where PUB / SUB are comma-separated topic patterns, or "-" for none.
set -euo pipefail

CA_DIR=${CA_DIR:-/etc/mosquitto/ca}
OUT_DIR=${OUT_DIR:-/opt/iot-cert/issued}
ACL=${ACL:-/etc/mosquitto/acl}
DAYS=${DAYS:-3650}

[[ $EUID -eq 0 ]] || { echo "must run as root (sudo)" >&2; exit 1; }
[[ -f "$CA_DIR/ca.crt" && -f "$CA_DIR/ca.key" ]] || { echo "no CA at $CA_DIR" >&2; exit 1; }

if [[ $# -eq 3 ]]; then
  NAME=$1; PUB=$2; SUB=$3
elif [[ $# -eq 0 ]]; then
  read -rp "device name (alnum, _ or -): " NAME
  read -rp "publish topics (comma-separated, '-' for none) [sensors/$NAME/#]: " PUB
  read -rp "subscribe topics (comma-separated, '-' for none) [commands/$NAME/#]: " SUB
  PUB=${PUB:-sensors/$NAME/#}
  SUB=${SUB:-commands/$NAME/#}
else
  echo "usage: issue.sh [NAME PUB SUB]" >&2; exit 1
fi

[[ "$NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}$ ]] \
  || { echo "invalid name (must match ^[A-Za-z0-9][A-Za-z0-9_-]{0,62}$)" >&2; exit 1; }

DEV=$OUT_DIR/$NAME
mkdir -p "$DEV"
cd "$DEV"

echo "[gen] key+csr+cert for $NAME"
openssl genrsa -out "$NAME.key" 2048 2>/dev/null
openssl req -new -key "$NAME.key" -out "$NAME.csr" \
  -subj "/CN=$NAME/O=HTL-IoT/OU=device" 2>/dev/null
openssl x509 -req -in "$NAME.csr" \
  -CA "$CA_DIR/ca.crt" -CAkey "$CA_DIR/ca.key" -CAcreateserial \
  -out "$NAME.crt" -days "$DAYS" -sha256 2>/dev/null
rm -f "$NAME.csr"
cp "$CA_DIR/ca.crt" ca.crt

# ----- update ACL ---------------------------------------------------------
TMP=$(mktemp)
awk -v name="$NAME" '
  $0 == "# === device:"name" BEGIN ===" { skip=1; next }
  $0 == "# === device:"name" END ==="   { skip=0; next }
  !skip
' "$ACL" > "$TMP"

{
  echo
  echo "# === device:$NAME BEGIN ==="
  echo "user $NAME"
  if [[ "$PUB" != "-" && -n "$PUB" ]]; then
    IFS=',' read -ra parts <<< "$PUB"
    for t in "${parts[@]}"; do
      t=$(echo "$t" | xargs)   # trim
      [[ -n "$t" ]] && echo "topic write $t"
    done
  fi
  if [[ "$SUB" != "-" && -n "$SUB" ]]; then
    IFS=',' read -ra parts <<< "$SUB"
    for t in "${parts[@]}"; do
      t=$(echo "$t" | xargs)
      [[ -n "$t" ]] && echo "topic read $t"
    done
  fi
  echo "# === device:$NAME END ==="
} >> "$TMP"

install -m 640 -o root -g mosquitto "$TMP" "$ACL"
rm -f "$TMP"

# ----- emit C/C++ header --------------------------------------------------
HEADER=${NAME}_certs.h
{
  echo "// Auto-generated by issue.sh — paste into your ESP32 sketch."
  echo "// Device: $NAME"
  echo "#pragma once"
  echo "static const char DEVICE_NAME[] = \"$NAME\";"
  echo "static const char CA_CERT_PEM[] PROGMEM = R\"PEM("
  cat ca.crt
  echo ")PEM\";"
  echo "static const char CLIENT_CERT_PEM[] PROGMEM = R\"PEM("
  cat "$NAME.crt"
  echo ")PEM\";"
  echo "static const char CLIENT_KEY_PEM[] PROGMEM = R\"PEM("
  cat "$NAME.key"
  echo ")PEM\";"
} > "$HEADER"

# ----- reload broker ------------------------------------------------------
systemctl kill -s HUP mosquitto

echo
echo "[ok] bundle: $DEV"
ls -la "$DEV"
echo
echo "Try:"
PUB_FIRST=$(echo "$PUB" | cut -d, -f1 | xargs)
[[ "$PUB_FIRST" == "-" || -z "$PUB_FIRST" ]] && PUB_FIRST="YOUR/TOPIC"
cat <<EOF
  mosquitto_pub -h 10.252.74.225 -p 8883 \\
    --cafile $DEV/ca.crt --cert $DEV/$NAME.crt --key $DEV/$NAME.key \\
    -t '$PUB_FIRST' -m 'hi'
EOF
